### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by rafaelbco** [eea/zptlint#2]
Since support for Chameleon was added I think a new release is worthwhile. 

PS.: Thanks for this very useful tool. It helped me a lot migrating a Plone 4.3 project to use Chameleon.

**Comment by avoinea** [comment]
@rafaelbco 

Unfortunately, as this is a fork from an old SVN, we do not have access to release it on PyPI https://pypi.python.org/pypi/zptlint 

That's why we released it on EEA eggrepo https://eggrepo.eea.europa.eu/d/zptlint/ and use it from there.

Until we find a way with the author (Balazs Ree), you can either install it from eggrepo.eea.europa.eu, or directly from github.

**Comment by avoinea** [comment]
@reebalazs Can you please help us with a new release of **zptlint**?!

**Comment by rafaelbco** [comment]
Thanks for your reply @avoinea
